@startuml
left to right direction
actor Pelanggan
actor Staf
actor Admin

usecase "Melihat Menu" as UC1
usecase "Membuat Pesanan" as UC2
usecase "Melacak Status Pesanan" as UC3
usecase "Memproses Pesanan" as UC4
usecase "Mengupdate Status Pesanan" as UC5
usecase "Mengelola Menu" as UC6
usecase "Melihat Laporan Penjualan" as UC7

Pelanggan --> UC1
Pelanggan --> UC2
Pelanggan --> UC3
Staf --> UC4
Staf --> UC5
Admin --> UC6
Admin --> UC7
@enduml
