@startuml usecase

actor "Pelanggan" as P
actor "Staf Restoran" as S
actor "Admin" as A

usecase "Melihat Menu" as UC1
usecase "Menambah Menu" as UC2
usecase "Mengedit Menu" as UC3
usecase "Menghapus Menu" as UC4
usecase "Memproses Pesanan" as UC5

P --> UC1 : Melihat Daftar Menu
S --> UC2 : Menambah Menu
S --> UC3 : Mengedit Menu
S --> UC4 : Menghapus Menu
A --> UC5 : Memproses Pesanan

@enduml
